/**
 * Configuration written on first start when no config file exists.
 *
 * It is intentionally minimal but complete: it validates as-is, so a fresh
 * container comes up and answers on /health with only the fallback route.
 */
export const DEFAULT_CONFIG_YAML = `# Generated by Gate on first start.
#
# Edit this file and restart the container. Gate never rewrites it: once the
# file exists it is left alone, and an invalid file stops startup rather than
# being repaired.

server:
  host: 0.0.0.0
  port: 6473
  max_body_size: 1MB
  upstream_timeout: 30s

  # Who may set X-Forwarded-*. Default false: trust nobody. Behind a proxy,
  # set this to its address or subnet so the real client IP survives.
  # trust_proxy: "172.18.0.0/16"

logging:
  level: info

jwt:
  algorithm: RS256

  # Generated alongside this file if they do not exist. They live in the
  # gate-data volume, never in the image.
  public_key: /data/keys/jwt_public.pem
  private_key: /data/keys/jwt_private.pem

  issuer: homelab-gateway

  audience:
    - homelab

  # Reject tokens with no exp claim. Gate has no revocation list, so an
  # expiry-less token cannot be invalidated without rotating the key pair.
  require_expiry: true

mapping:
  enabled: true

token_log:
  path: /data/tokens.jsonl

# Upstreams Gate is allowed to reach. A route can only name a service listed
# here — a client can never supply a URL of its own.
services:
  fallback:
    url: http://fallback:6473

  # n8n:
  #   url: http://n8n:5678
  #
  # grafana-main:
  #   url: http://grafana:3000

routes:
  # Exactly one fallback is required. It never authenticates and its path is
  # never rewritten.
  - fallback:
      service: fallback

  # Normal routes are matched by target, taken from the JWT "target" claim or
  # the X-Target header. "service" defaults to the target name and "auth"
  # defaults to true.
  #
  # - target: n8n
  #   mapping:
  #     path:
  #       strip_prefix: /n8n/
  #
  # - target: grafana
  #   service: grafana-main
  #   auth: false
`;
